-- Run after database-schema.sql in the MilesWeb MySQL database.
-- The PHP endpoint enforces these checks before inserting:
--   * allowed enquiry types only
--   * valid name and email values
--   * known payload fields only
--   * payload size and field length limits
--   * maximum three submissions per email in 15 minutes
--   * no public read/update/delete endpoint is exposed
